export default [
  {
    name: "WETC",
    contractChain: "0x13881",
    id: 2,
    contract: {
      name: "CauldronMediumRiskV1",
      address: "0xE075BB370e9139fD5B24Eb1dAfabD56bEdFed34D",
      abi: [
        {
          inputs: [
            {
              internalType: "contract IBentoBoxV1",
              name: "bentoBox_",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "magicInternetMoney_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint128",
              name: "accruedAmount",
              type: "uint128",
            },
          ],
          name: "LogAccrue",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "share",
              type: "uint256",
            },
          ],
          name: "LogAddCollateral",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "part",
              type: "uint256",
            },
          ],
          name: "LogBorrow",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "rate",
              type: "uint256",
            },
          ],
          name: "LogExchangeRate",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newFeeTo",
              type: "address",
            },
          ],
          name: "LogFeeTo",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "share",
              type: "uint256",
            },
          ],
          name: "LogRemoveCollateral",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "part",
              type: "uint256",
            },
          ],
          name: "LogRepay",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "feeTo",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "feesEarnedFraction",
              type: "uint256",
            },
          ],
          name: "LogWithdrawFees",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [],
          name: "accrue",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "accrueInfo",
          outputs: [
            { internalType: "uint64", name: "lastAccrued", type: "uint64" },
            { internalType: "uint128", name: "feesEarned", type: "uint128" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "bool", name: "skim", type: "bool" },
            { internalType: "uint256", name: "share", type: "uint256" },
          ],
          name: "addCollateral",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "bentoBox",
          outputs: [
            { internalType: "contract IBentoBoxV1", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "borrow",
          outputs: [
            { internalType: "uint256", name: "part", type: "uint256" },
            { internalType: "uint256", name: "share", type: "uint256" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claimOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "collateral",
          outputs: [
            { internalType: "contract IERC20", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint8[]", name: "actions", type: "uint8[]" },
            { internalType: "uint256[]", name: "values", type: "uint256[]" },
            { internalType: "bytes[]", name: "datas", type: "bytes[]" },
          ],
          name: "cook",
          outputs: [
            { internalType: "uint256", name: "value1", type: "uint256" },
            { internalType: "uint256", name: "value2", type: "uint256" },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "exchangeRate",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "feeTo",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
          name: "init",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address[]", name: "users", type: "address[]" },
            {
              internalType: "uint256[]",
              name: "maxBorrowParts",
              type: "uint256[]",
            },
            { internalType: "address", name: "to", type: "address" },
            {
              internalType: "contract ISwapper",
              name: "swapper",
              type: "address",
            },
          ],
          name: "liquidate",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "magicInternetMoney",
          outputs: [
            { internalType: "contract IERC20", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "masterContract",
          outputs: [
            {
              internalType: "contract CauldronMediumRiskV1",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "oracle",
          outputs: [
            { internalType: "contract IOracle", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleData",
          outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingOwner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "reduceSupply",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "share", type: "uint256" },
          ],
          name: "removeCollateral",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "bool", name: "skim", type: "bool" },
            { internalType: "uint256", name: "part", type: "uint256" },
          ],
          name: "repay",
          outputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "newFeeTo", type: "address" },
          ],
          name: "setFeeTo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalBorrow",
          outputs: [
            { internalType: "uint128", name: "elastic", type: "uint128" },
            { internalType: "uint128", name: "base", type: "uint128" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCollateralShare",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "newOwner", type: "address" },
            { internalType: "bool", name: "direct", type: "bool" },
            { internalType: "bool", name: "renounce", type: "bool" },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "updateExchangeRate",
          outputs: [
            { internalType: "bool", name: "updated", type: "bool" },
            { internalType: "uint256", name: "rate", type: "uint256" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "userBorrowPart",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "userCollateralShare",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawFees",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    token: {
      name: "WETC",
      decimals: 18,
      address: "0xF62b40F2f32a299D7387C3472A69A5a1bf1De664",
      oracleId: 1,
      oracleDatas: {
        multiply: "0x0000000000000000000000000000000000000000",
        divide: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419",
        decimals: 10,
      },
      abi: [
        {
          name: "Transfer",
          inputs: [
            { type: "address", name: "sender", indexed: true },
            { type: "address", name: "receiver", indexed: true },
            { type: "uint256", name: "value", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "Approval",
          inputs: [
            { type: "address", name: "owner", indexed: true },
            { type: "address", name: "spender", indexed: true },
            { type: "uint256", name: "value", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyAdded",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "debtRatio", indexed: false },
            { type: "uint256", name: "minDebtPerHarvest", indexed: false },
            { type: "uint256", name: "maxDebtPerHarvest", indexed: false },
            { type: "uint256", name: "performanceFee", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyReported",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "gain", indexed: false },
            { type: "uint256", name: "loss", indexed: false },
            { type: "uint256", name: "debtPaid", indexed: false },
            { type: "uint256", name: "totalGain", indexed: false },
            { type: "uint256", name: "totalLoss", indexed: false },
            { type: "uint256", name: "totalDebt", indexed: false },
            { type: "uint256", name: "debtAdded", indexed: false },
            { type: "uint256", name: "debtRatio", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateGovernance",
          inputs: [{ type: "address", name: "governance", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateManagement",
          inputs: [{ type: "address", name: "management", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateGuestList",
          inputs: [{ type: "address", name: "guestList", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateRewards",
          inputs: [{ type: "address", name: "rewards", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateDepositLimit",
          inputs: [{ type: "uint256", name: "depositLimit", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdatePerformanceFee",
          inputs: [{ type: "uint256", name: "performanceFee", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateManagementFee",
          inputs: [{ type: "uint256", name: "managementFee", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateGuardian",
          inputs: [{ type: "address", name: "guardian", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "EmergencyShutdown",
          inputs: [{ type: "bool", name: "active", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "UpdateWithdrawalQueue",
          inputs: [{ type: "address[20]", name: "queue", indexed: false }],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyUpdateDebtRatio",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "debtRatio", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyUpdateMinDebtPerHarvest",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "minDebtPerHarvest", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyUpdateMaxDebtPerHarvest",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "maxDebtPerHarvest", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyUpdatePerformanceFee",
          inputs: [
            { type: "address", name: "strategy", indexed: true },
            { type: "uint256", name: "performanceFee", indexed: false },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyMigrated",
          inputs: [
            { type: "address", name: "oldVersion", indexed: true },
            { type: "address", name: "newVersion", indexed: true },
          ],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyRevoked",
          inputs: [{ type: "address", name: "strategy", indexed: true }],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyRemovedFromQueue",
          inputs: [{ type: "address", name: "strategy", indexed: true }],
          anonymous: false,
          type: "event",
        },
        {
          name: "StrategyAddedToQueue",
          inputs: [{ type: "address", name: "strategy", indexed: true }],
          anonymous: false,
          type: "event",
        },
        {
          name: "initialize",
          outputs: [],
          inputs: [
            { type: "address", name: "token" },
            { type: "address", name: "governance" },
            { type: "address", name: "rewards" },
            { type: "string", name: "nameOverride" },
            { type: "string", name: "symbolOverride" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "initialize",
          outputs: [],
          inputs: [
            { type: "address", name: "token" },
            { type: "address", name: "governance" },
            { type: "address", name: "rewards" },
            { type: "string", name: "nameOverride" },
            { type: "string", name: "symbolOverride" },
            { type: "address", name: "guardian" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "apiVersion",
          outputs: [{ type: "string", name: "" }],
          inputs: [],
          stateMutability: "pure",
          type: "function",
          gas: 4519,
        },
        {
          name: "setName",
          outputs: [],
          inputs: [{ type: "string", name: "name" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 107017,
        },
        {
          name: "setSymbol",
          outputs: [],
          inputs: [{ type: "string", name: "symbol" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 71867,
        },
        {
          name: "setGovernance",
          outputs: [],
          inputs: [{ type: "address", name: "governance" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 36338,
        },
        {
          name: "acceptGovernance",
          outputs: [],
          inputs: [],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37610,
        },
        {
          name: "setManagement",
          outputs: [],
          inputs: [{ type: "address", name: "management" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37748,
        },
        {
          name: "setGuestList",
          outputs: [],
          inputs: [{ type: "address", name: "guestList" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37778,
        },
        {
          name: "setRewards",
          outputs: [],
          inputs: [{ type: "address", name: "rewards" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37808,
        },
        {
          name: "setLockedProfitDegration",
          outputs: [],
          inputs: [{ type: "uint256", name: "degration" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 36516,
        },
        {
          name: "setDepositLimit",
          outputs: [],
          inputs: [{ type: "uint256", name: "limit" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37768,
        },
        {
          name: "setPerformanceFee",
          outputs: [],
          inputs: [{ type: "uint256", name: "fee" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37902,
        },
        {
          name: "setManagementFee",
          outputs: [],
          inputs: [{ type: "uint256", name: "fee" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 37932,
        },
        {
          name: "setGuardian",
          outputs: [],
          inputs: [{ type: "address", name: "guardian" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 39176,
        },
        {
          name: "setEmergencyShutdown",
          outputs: [],
          inputs: [{ type: "bool", name: "active" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 39247,
        },
        {
          name: "setWithdrawalQueue",
          outputs: [],
          inputs: [{ type: "address[20]", name: "queue" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 763923,
        },
        {
          name: "transfer",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "receiver" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 76913,
        },
        {
          name: "transferFrom",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "sender" },
            { type: "address", name: "receiver" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 116676,
        },
        {
          name: "approve",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 38334,
        },
        {
          name: "increaseAllowance",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 40375,
        },
        {
          name: "decreaseAllowance",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 40399,
        },
        {
          name: "permit",
          outputs: [{ type: "bool", name: "" }],
          inputs: [
            { type: "address", name: "owner" },
            { type: "address", name: "spender" },
            { type: "uint256", name: "amount" },
            { type: "uint256", name: "expiry" },
            { type: "bytes", name: "signature" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 81327,
        },
        {
          name: "totalAssets",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 4303,
        },
        {
          name: "deposit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "deposit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "uint256", name: "_amount" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "deposit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [
            { type: "uint256", name: "_amount" },
            { type: "address", name: "recipient" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "maxAvailableShares",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 379843,
        },
        {
          name: "withdraw",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "withdraw",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "uint256", name: "maxShares" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "withdraw",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [
            { type: "uint256", name: "maxShares" },
            { type: "address", name: "recipient" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "withdraw",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [
            { type: "uint256", name: "maxShares" },
            { type: "address", name: "recipient" },
            { type: "uint256", name: "maxLoss" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "pricePerShare",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 17509,
        },
        {
          name: "addStrategy",
          outputs: [],
          inputs: [
            { type: "address", name: "strategy" },
            { type: "uint256", name: "debtRatio" },
            { type: "uint256", name: "minDebtPerHarvest" },
            { type: "uint256", name: "maxDebtPerHarvest" },
            { type: "uint256", name: "performanceFee" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 1486241,
        },
        {
          name: "updateStrategyDebtRatio",
          outputs: [],
          inputs: [
            { type: "address", name: "strategy" },
            { type: "uint256", name: "debtRatio" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 115406,
        },
        {
          name: "updateStrategyMinDebtPerHarvest",
          outputs: [],
          inputs: [
            { type: "address", name: "strategy" },
            { type: "uint256", name: "minDebtPerHarvest" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 42654,
        },
        {
          name: "updateStrategyMaxDebtPerHarvest",
          outputs: [],
          inputs: [
            { type: "address", name: "strategy" },
            { type: "uint256", name: "maxDebtPerHarvest" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 42684,
        },
        {
          name: "updateStrategyPerformanceFee",
          outputs: [],
          inputs: [
            { type: "address", name: "strategy" },
            { type: "uint256", name: "performanceFee" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 41464,
        },
        {
          name: "migrateStrategy",
          outputs: [],
          inputs: [
            { type: "address", name: "oldVersion" },
            { type: "address", name: "newVersion" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 1141973,
        },
        {
          name: "revokeStrategy",
          outputs: [],
          inputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "revokeStrategy",
          outputs: [],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "addStrategyToQueue",
          outputs: [],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 1197130,
        },
        {
          name: "removeStrategyFromQueue",
          outputs: [],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "nonpayable",
          type: "function",
          gas: 23093586,
        },
        {
          name: "debtOutstanding",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "debtOutstanding",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "creditAvailable",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "creditAvailable",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "availableDepositLimit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 10108,
        },
        {
          name: "expectedReturn",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "expectedReturn",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "address", name: "strategy" }],
          stateMutability: "view",
          type: "function",
        },
        {
          name: "report",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [
            { type: "uint256", name: "gain" },
            { type: "uint256", name: "loss" },
            { type: "uint256", name: "_debtPayment" },
          ],
          stateMutability: "nonpayable",
          type: "function",
          gas: 1009335,
        },
        {
          name: "sweep",
          outputs: [],
          inputs: [{ type: "address", name: "token" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "sweep",
          outputs: [],
          inputs: [
            { type: "address", name: "token" },
            { type: "uint256", name: "amount" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          name: "name",
          outputs: [{ type: "string", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 9143,
        },
        {
          name: "symbol",
          outputs: [{ type: "string", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 8196,
        },
        {
          name: "decimals",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 2801,
        },
        {
          name: "balanceOf",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "address", name: "arg0" }],
          stateMutability: "view",
          type: "function",
          gas: 3046,
        },
        {
          name: "allowance",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [
            { type: "address", name: "arg0" },
            { type: "address", name: "arg1" },
          ],
          stateMutability: "view",
          type: "function",
          gas: 3291,
        },
        {
          name: "totalSupply",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 2891,
        },
        {
          name: "token",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 2921,
        },
        {
          name: "governance",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 2951,
        },
        {
          name: "management",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 2981,
        },
        {
          name: "guardian",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3011,
        },
        {
          name: "guestList",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3041,
        },
        {
          name: "strategies",
          outputs: [
            { type: "uint256", name: "performanceFee" },
            { type: "uint256", name: "activation" },
            { type: "uint256", name: "debtRatio" },
            { type: "uint256", name: "minDebtPerHarvest" },
            { type: "uint256", name: "maxDebtPerHarvest" },
            { type: "uint256", name: "lastReport" },
            { type: "uint256", name: "totalDebt" },
            { type: "uint256", name: "totalGain" },
            { type: "uint256", name: "totalLoss" },
          ],
          inputs: [{ type: "address", name: "arg0" }],
          stateMutability: "view",
          type: "function",
          gas: 11394,
        },
        {
          name: "withdrawalQueue",
          outputs: [{ type: "address", name: "" }],
          inputs: [{ type: "uint256", name: "arg0" }],
          stateMutability: "view",
          type: "function",
          gas: 3210,
        },
        {
          name: "emergencyShutdown",
          outputs: [{ type: "bool", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3131,
        },
        {
          name: "depositLimit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3161,
        },
        {
          name: "debtRatio",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3191,
        },
        {
          name: "totalDebt",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3221,
        },
        {
          name: "lastReport",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3251,
        },
        {
          name: "activation",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3281,
        },
        {
          name: "lockedProfit",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3311,
        },
        {
          name: "lockedProfitDegration",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3341,
        },
        {
          name: "rewards",
          outputs: [{ type: "address", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3371,
        },
        {
          name: "managementFee",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3401,
        },
        {
          name: "performanceFee",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3431,
        },
        {
          name: "nonces",
          outputs: [{ type: "uint256", name: "" }],
          inputs: [{ type: "address", name: "arg0" }],
          stateMutability: "view",
          type: "function",
          gas: 3676,
        },
        {
          name: "DOMAIN_SEPARATOR",
          outputs: [{ type: "bytes32", name: "" }],
          inputs: [],
          stateMutability: "view",
          type: "function",
          gas: 3491,
        },
      ],
    },
    pairToken: {
      name: "MIM",
      decimals: 18,
      address: "0xD40c00998d74c6d67de594cf7c6893d11C0A3136",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "", type: "address" },
            { internalType: "address", name: "", type: "address" },
          ],
          name: "allowance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "approve",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "balanceOf",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claimOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastMint",
          outputs: [
            { internalType: "uint128", name: "time", type: "uint128" },
            { internalType: "uint128", name: "amount", type: "uint128" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "clone", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            {
              internalType: "contract IBentoBoxV1",
              name: "bentoBox",
              type: "address",
            },
          ],
          name: "mintToBentoBox",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "nonces",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingOwner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "owner_", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "deadline", type: "uint256" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
          ],
          name: "permit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "transfer",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "from", type: "address" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "transferFrom",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "newOwner", type: "address" },
            { internalType: "bool", name: "direct", type: "bool" },
            { internalType: "bool", name: "renounce", type: "bool" },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    stabilityFee: 12.5,
    interest: 1.5,
    ltv: 75,
    initialMax: 300,
    swapContractInfo: {
      address: "0x9702B517ACc393e95724a8143FB502052Fed9d4D",
      abi: [
        {
          inputs: [
            {
              internalType: "contract IBentoBoxV1",
              name: "bentoBox_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "MIM",
          outputs: [
            { internalType: "contract IERC20", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIM3POOL",
          outputs: [
            { internalType: "contract CurvePool", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TETHER",
          outputs: [
            { internalType: "contract TetherToken", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WETH_VAULT",
          outputs: [
            { internalType: "contract YearnVault", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "bentoBox",
          outputs: [
            { internalType: "contract IBentoBoxV1", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "recipient", type: "address" },
            { internalType: "uint256", name: "shareToMin", type: "uint256" },
            { internalType: "uint256", name: "shareFrom", type: "uint256" },
          ],
          name: "swap",
          outputs: [
            { internalType: "uint256", name: "extraShare", type: "uint256" },
            { internalType: "uint256", name: "shareReturned", type: "uint256" },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
  },
];
